name: Docker Image CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag java-simple:$(date +%s)

  deploy:
    name: Deploy with Docker Compose
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Compose
      uses: docker/compose-action@v2

    - name: Build and deploy with Docker Compose
      run: |
        docker-compose build
        docker-compose up -d

    - name: Clean up unused Docker images
      run: docker image prune -f
